### ISSUE TITLE
As an administrator, I want to have access to documentation to be able to create new challenges. 

### ISSUE THREAD

**Issue by EthanIsakson** [acasi-ctf/ctf#10]
# Acceptance Criteria

- [x] Administrators can easily access documentation that shows them how to create and edit challenges and deploy them to the platform. 
- [x] #30

**Comment by lgorence** [comment]
Pushing this to sprint 3, the systems required are not complete and will not be by the end of sprint 2, pushing this to sprint 3.

**Comment by lgorence** [comment]
With pull request #192, and the documentation linked here, this is complete! Once that PR is closed, this issue will close too.
https://acasi-ctf.github.io/docs/creating_challenges.html#building-the-challenge-set
