### ISSUE TITLE
As a user, I only want to see the button for ingress if the challenge requires it so that it does not cause confusion.

### ISSUE THREAD

**Issue by lgorence** [acasi-ctf/ctf#103]
Some challenges will present a webpage for the user to interact with, and this information will be available via the frontend API.

**Blocked by #102**

**Comment by DungLe2911** [comment]
Along with comment in issue #93, I can toggle on/off the visibility of the button if the challenge links to another page. However, I need visuallize (in figma) where it should be in the page

**Comment by lgorence** [comment]
Pushing this to the final sprint.
