### ISSUE TITLE
Come up with Kali Linux tutorial environment and challenge

### ISSUE THREAD

**Issue by colbycocking** [acasi-ctf/ctf#104]
The purpose of the Kali Linux challenges are to familiarize users with the tools they they will need to start hacking.
- [x] Come up with tutorial challenge
- [x] Come up with environment requirements
- [x] get necessary documentation

**Comment by EthanIsakson** [comment]
Container is up and running successfully (locally). Template environment settings are known and included in image. 
Strings challenge was created and is complete. Still lacking documentation for strings tutorial, more specific walk throughs found here: #114
Gathered neccessary documentation for Docker Files, which I will begin moving into the cluster under: #109
