### ISSUE TITLE
Get Kali Linux Docker Container Created

### ISSUE THREAD

**Issue by EthanIsakson** [acasi-ctf/ctf#109]
- [x] Get Image working in container.

- [x] #110

**Comment by EthanIsakson** [comment]
Kali Linux Image has been created and run locally. It is currently just a fulling in image for kali: kalilinux/kali-rolling, I was able to find a headless install of kali linux top 25 tools.

**Comment by EthanIsakson** [comment]
Docker File Draft is created and just in need of testing and final implementation. 

Hoping to work with @lgorence on this in the next week or so. 
https://github.com/acasi-ctf/ctf/commit/9ba31b2a79fb2510a69853b369de45e3dcd72a4f

**Comment by colbycocking** [comment]
@EthanIsakson status report

**Comment by EthanIsakson** [comment]
Waiting on successfully getting this working in cluster. Going to need to discuss this with Logan when I get some free time.
