### ISSUE TITLE
Get my docker images running in cluster.

### ISSUE THREAD

**Issue by EthanIsakson** [acasi-ctf/ctf#110]
I have a couple images for Kali-Linux, smaller versions and more built out images with more tools. However, these are still being run locally on my machine. 

Need to work with @lgorence to get these Docker Files correctly configured to run in our environment. 

- [ ] Get docker container running off of Docker Run Files so Logan can run it in the cluster.

**Comment by EthanIsakson** [comment]
Holding on this until I can schedule a time to meet with Logan.

**Comment by colbycocking** [comment]
Blocked by lack of time and experience.

**Comment by EthanIsakson** [comment]
Closed with #134
