### ISSUE TITLE
Draft Up Future Commands

### ISSUE THREAD

**Issue by EthanIsakson** [acasi-ctf/ctf#111]
Want to get a start on where I plan to go in the future commands wise, so far I have found an accurate way to show the advantage of using the command strings to explorer readable text within a file.

Rather than moving through commands one at a time I want to write up a rough of idea of the next commands I would like to touch on and how I expect to go about them.

**Comment by EthanIsakson** [comment]
Added Tools file, last commit - 17e013fa06c23cbe251ea3b0b82801fdd3b11cd7
Details commands I think would be good to cover.

**Comment by lgorence** [comment]
PR #134 was merged, closing this.
