### ISSUE TITLE
As an administrator, I want to be able to view user reports and feedback so that I can make improvements to the system. 

### ISSUE THREAD

**Issue by EthanIsakson** [acasi-ctf/ctf#13]
# Acceptance Criteria

- [ ] Be able to view user submitted comments. 
- [ ] Separate user comments by type (e.g., bug report, feature request, other) 
...

**Comment by lgorence** [comment]
We are getting this task for free, because we're using Qualtrics for feedback! Closing this an reassigning it to Sprint 1, because we did already finish it.
