### ISSUE TITLE
As an administrator I would like to access to a comprehensive list of useful penetration testing tools for future challenges

### ISSUE THREAD

**Issue by EthanIsakson** [acasi-ctf/ctf#136]
A follow up to #111

Need to add more info to Tools.md doc:

-  man page links
- more detailed descriptions
- installation instructions.

**Comment by EthanIsakson** [comment]
Didn't quite get this finished up. Will have is done early this week.

**Comment by colbycocking** [comment]
@EthanIsakson update this issues format please.
