### ISSUE TITLE
Refresh Page Bug

### ISSUE THREAD

**Issue by colbycocking** [acasi-ctf/ctf#140]
When you go to a challenge and refresh the page, when you log back in you are immediately taken back to the challenge upon logging in but the menus do not load.

**Comment by DungLe2911** [comment]
This has been fixed in commit 'adc94b76c100d54efdf21e519df9d29ef1bcd462'

**Comment by DungLe2911** [comment]
I am getting this warning as well, not a big deal but might be something to consider fixing it:
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

**Comment by colbycocking** [comment]
Richard and Logan completd.
