### ISSUE TITLE
As a user, I should be able to pick from at least two challenges that cover unique and interesting topics. 

### ISSUE THREAD

**Issue by EthanIsakson** [acasi-ctf/ctf#15]
This is a continually moving user story! It will likely be in-progress the entirety of this first semester.

# Acceptance Criteria

- [x] User can pick from at least two different challenges designed by our team. 
- [x] User can decide between an easier or more difficult topic, and the difficult one may depend on skills learned from the easy one. 
...

**Comment by EthanIsakson** [comment]
Sub-Challenge 1:

Created a basic login webpage so far. Still working on adding additional levels to more closely represent a real world website (JS Files and CSS etc).

Next Steps are to finalize the page.

**Comment by EthanIsakson** [comment]
As of now we have 3 fully working challenges, however waiting on some adaptations so they can be added to our sys in order to be considered fully done.

**Comment by EthanIsakson** [comment]
Still waiting on ensuring out challenges spin up as desired.

**Comment by colbycocking** [comment]
The acceptance criteria was 2 challenges, We are past that I am closing this as complete.
