### ISSUE TITLE
Rename Kali challenge set

### ISSUE THREAD

**Issue by lgorence** [acasi-ctf/ctf#170]
Something Renuka has wanted to change is to rename the Kali challenge set to something else more fitting.  Something like "penetration testing utilities". If you simply want to rename the directories and leave the container image URL the same, that is fine as it's not user-facing.

**Comment by EthanIsakson** [comment]
Sounds like this is more time sensitive than I thought so moving it to this sprint so I can get it finished.

**Comment by EthanIsakson** [comment]
Renamed Linux Tools to Penetration Testing Utilities in my documentation, modified directories and renamed pentesting to avoid confusion. 

Images are not public facing so not changing these, but if needed could be done.

**Comment by EthanIsakson** [comment]
Nevermind, renaming images. Going to bug me to not have everything on the same page.

**Comment by EthanIsakson** [comment]
Updated my old images for Kali Tutorials and renamed it to Pentesting so it lines up with our new directories.

**Comment by Renukanadkarni** [comment]
Thanks Ethan!

**Comment by EthanIsakson** [comment]
No problem!
