### ISSUE TITLE
As a user I want a leaderboard page so I can see my standings compared to my peers.

### ISSUE THREAD

**Issue by lgorence** [acasi-ctf/ctf#186]
Create the leaderboard page in the UI using the respective API at `/api/leaderboard`.

Create a paginated leaderboard using ID.
- [x] #185
- [x] #184 
- [x] Create a template table to for the Leaber board display
- [ ] Make some ehancement on the display of the leader board so it looks better
- [x] API call to backend to display some made up information for now
- [x] Make sure the table is sorted based on how many challenges has completed

**Comment by lgorence** [comment]
This has also been deployed to the production environment.

**Comment by DungLe2911** [comment]
- [ ] Create a template table to for the Leaber board display
- [ ] Make some ehancement on the display of the leader board
- [ ] API call to backend to display some made up information for now

**Comment by colbycocking** [comment]
Closed with PR #207
