### ISSUE TITLE
As a user, I want the dialog after inputting a flag to look good and blend into the page

### ISSUE THREAD

**Issue by lgorence** [acasi-ctf/ctf#193]
Currently, the flag submission dialog is a simple `window.alert`, which are generally not that great looking and don't blend in with the design of the page. We would like to use a Material UI dialog, or something similar to do this.

# Acceptance criteria
* The submission results dialog should look closer to the normal page design.

# Before
![image](https://user-images.githubusercontent.com/1173922/142707931-74c201c6-8feb-4d69-8992-dae9cdb330df.png)

**Comment by colbycocking** [comment]
Closed with PR #207
