### ISSUE TITLE
As a sponsor I want the page to look clean by Monday 11/22 so that I can demonstrate it to my CEO and his directors.

### ISSUE THREAD

**Issue by colbycocking** [acasi-ctf/ctf#199]
Temporarily hide everything that doesn't look beta ready for Renuka's demonstration to CEO.

**Comment by DungLe2911** [comment]
give me more detail on this of what I need to hide

**Comment by lgorence** [comment]
@colbycocking This can probably be closed now, right?

**Comment by colbycocking** [comment]
Yep
