### ISSUE TITLE
As a user, I want to be able to run this in an online shell environment, so I do not have to install anything on my personal computer. 

### ISSUE THREAD

**Issue by EthanIsakson** [acasi-ctf/ctf#2]
# Acceptance Criteria

- [x] Application runs in a web browser.

**Comment by colbycocking** [comment]
The terminal currently runs in the browser. I do not think it has been migrated to a cloud service yet.

**Comment by lgorence** [comment]
It has not been migrated to the cloud, but it is running in Kubernetes now, which is a lot of the work.

**Comment by lgorence** [comment]
Moved to sprint 2, as this is likely going to be a continually evolving task for me

**Comment by colbycocking** [comment]
As far as I am concerned moving it to the cloud is not as important as showing that we have the ability to migrate it there and have no issues. We may end up pushing this to sprint 3 depending on how the rest of sprint 2 goes.

**Comment by colbycocking** [comment]
I'm going to mark this as complete and create a new issue for sprint 3 for getting this onto the cloud.
