### ISSUE TITLE
Get Documentation for first challenge set

### ISSUE THREAD

**Issue by colbycocking** [acasi-ctf/ctf#22]
The following are subtasks that need to get completed for challenges by the end of sprint 2.
- [x] #34 
- [x] #35 
- [x] #36 
- [x] #37
- [x] #38

**Comment by colbycocking** [comment]
I am primarily worried about the finding the hidden flag in the HTML scenario.

**Comment by colbycocking** [comment]
I feel like we are falling a bit behind in the challenge category. I am not blaming anyone, but I think we need to get our challenges for the first challenge set figured out. Zhaohu had a good cipher challenge, but we need more documentation for it. How does a Caesar cipher work and such.

**Comment by EllisHZH** [comment]
I will collect as much as information about it, and finish it in this two days.

**Comment by lgorence** [comment]
@colbycocking We should probably assign this to sprint 2, so that we can close out the sprint 1 milestone.

**Comment by colbycocking** [comment]
I haven't heard of any progress on the challenges. I broke this issue down into 5 separate tickets for each challenge and linked them to this one. Please keep me updated with any progress you guys have made.

**Comment by colbycocking** [comment]
I'm going to probably close this issue because we have a first challenge set and all documentation because of how we reorganized. When I do I will create a new issue for the new challenge set and put it in semester 2. For a final completion.

**Comment by DungLe2911** [comment]
See see all the check marks for #37 and #38  has been checked, can this issue be closed ?

**Comment by colbycocking** [comment]
Yeah, I was going to modify this issue, but I will just close it for now and create a new one with the updated information.
