### ISSUE TITLE
Safari fails to connect over WebSocket for gRPC-Web

### ISSUE THREAD

**Issue by lgorence** [acasi-ctf/ctf#23]
Reported by @kendfinger, he might fix it for us and PR it. If he doesn't, I'll get more details from him and fix it when I have the time.

**Comment by lgorence** [comment]
Pushing to this summer / next semester. Not an important issue right now.

**Comment by lgorence** [comment]
Moved to the future board, Safari support isn't really a huge priority for us.

**Comment by colbycocking** [comment]
@lgorence can you fix this so it adhere's to the rubric's requirements?

**Comment by lgorence** [comment]
This issue isn't reproducible by myself or the person who reported it initially. Closing.
