### ISSUE TITLE
Plan out Database schema

### ISSUE THREAD

**Issue by colbycocking** [acasi-ctf/ctf#28]
We need to decide on a method of storing the documentation other than putting stuff in teams. I think we need to get a database started that contains challenge topics > challenge sets > challenges > everything that is required for a challenge. I have little experience with databases though so input would be appreciated.

**Comment by DungLe2911** [comment]
I have a little bit of understanding on the description of this issues that whether of not this is referring about the attributes to describe a challenge, we should include in the database? or is it about something else?

**Comment by lgorence** [comment]
Colby and I talked about this about half an hour ago, and we're going to be standardizing on Markdown for writing documentation in. It's very easily compiled to HTML, and is a lot more concise and readable than HTML is. But, for storing actual details about how a challenge is presented in the UI, is going to take a lot more thought. A lot of this is currently in flux in my head (sorry, this is the way I tend to think through things), but I can put some of it down on paper and see what everyone thinks if that is requested.

**Comment by DungLe2911** [comment]
I amma go ahead and put down here the schema for the challenge that I come up with, so we have something to start. We can have some adjustment later if we need:
- Challenge Name
- Category
- Score
- Author:
      + First Name
      + Last Name
- Flag
- Solved
- Hint
- Created date:
        + Day
        + Month
        + Year
        + Time

**Comment by colbycocking** [comment]
I'd like to discuss this more in our team meeting tomorrow.

**Comment by lgorence** [comment]
This is mostly done for challenge sets, challenges, and their respective documentation. Pull request #33 will close this issue. Future database tables will be planned for when necessary.
