### ISSUE TITLE
UI/Backend diagram

### ISSUE THREAD

**Issue by colbycocking** [acasi-ctf/ctf#29]
We really need to do some planning for the design of the UI. I would like to get a UML diagram of some sort done that shows how the pages and content are managed.  Once we have a general outline of what the site design will look like we can start implementing the components. Overall this should save time as we won't be just working off the top of our heads which is difficult in a group setting. This is mainly for Richard and I but welcome any input Logan has.

- [x] Draw up UML diagram with UI design.

**Comment by lgorence** [comment]
What kind of UML diagram are you looking for? I'm not sure which kind applies the best to what you're trying to do, but I only know two off the top of my head.

**Comment by colbycocking** [comment]
A UML sequence diagram would be the most likely I think.

**Comment by colbycocking** [comment]
I ended up just more or less using a class diagram to show how the challenge sets and challenges are connected. I will update it if we make any changes.
