### ISSUE TITLE
As a user, I want to be able to view available challenges so I can select one to attempt. 

### ISSUE THREAD

**Issue by EthanIsakson** [acasi-ctf/ctf#3]
# Acceptance Criteria

- [x] Home screen displays available challenges that the user can select from which will spin up a container.

**Comment by colbycocking** [comment]
I'm pushing this to sprint 3 because we have the UI portion of this, but we don't have access to the API's to create the UI components yet. Correct me if I'm wrong, but outside of Logan opening his local system to me, we have to get this on the cloud for that to happen correct? @lgorence

**Comment by lgorence** [comment]
> I'm pushing this to sprint 3 because we have the UI portion of this, but we don't have access to the API's to create the UI components yet. Correct me if I'm wrong, but outside of Logan opening his local system to me, we have to get this on the cloud for that to happen correct? @lgorence 

@colbycocking Mostly. Either I open a port to my laptop running the front end API, or I get it running in Kubernetes, which is either my local cluster or one in the cloud.

**Comment by DungLe2911** [comment]
I think We are good to close this one. We have a Challenge Selection page working for showing all the available challenge
