### ISSUE TITLE
Webpage Structure Challenge

### ISSUE THREAD

**Issue by colbycocking** [acasi-ctf/ctf#34]
- [x] Write challenge description
- [x] Write challenge
- [x] Write documentation in .md file

**Comment by EthanIsakson** [comment]
Summary of challenge 1. We will be providing the user with a fairly standard webpage. I will provide basic intro into webpage formats and common structure. And instruct them to search through the source files for a hidden key.

**Comment by EllisHZH** [comment]
Summary of challenge 1. It is Caesar cipher challenge. The challenge will create 10 letter random string and a random number for encode by Caesar cipher. User need to find out the original string.

**Comment by colbycocking** [comment]
This is supposed to be the basic web structure challenge. @EllisHZH All of the cipher challenges go in challenge 2. They are sub challenges of 1 challenge in the challenge set.

**Comment by EthanIsakson** [comment]
Added bash script to ctf/challenges/storage/Challenge-WebFormat/
Docker file hosted my local machine till we proceed to integrate with the cluster.

**Comment by EthanIsakson** [comment]
Added brief Documentation and Description files for Challenge: Webpage Structure. 

Still feel the need to review both files since it is the first challenge and further challenge docs will likely fall a similar format.

**Comment by EthanIsakson** [comment]
Looks like there may need to be some modifications to this down the road but I will consider this closed for now.
