### ISSUE TITLE
Create Cipher Challenge

### ISSUE THREAD

**Issue by colbycocking** [acasi-ctf/ctf#35]
- [x] Write challenge description
- [x] Write challenge
- [x] Write documentation in .md file
- [x] put all the cipher challenges as tasks in this issue.

**Comment by EllisHZH** [comment]
Summary of challenge 2. It is Letter to number challenge. The challenge will create 10 letter random string and convert the letter to number. User need to find out the original string.

**Comment by colbycocking** [comment]
So, it was my understanding that all the ciphers were one overall challenge. Is that not the case?

**Comment by EllisHZH** [comment]
Cipher Challege - Phrase 1 - Finished. There are python programs. It has 3 small challenges which are Caesear Cipher, Number to Letter Cipher, and Reverse Cipher. A mix change challenge which combine all three together. Addition Challenge, Mosre Code.

**Comment by colbycocking** [comment]
Need to go over documentation for minor editing but otherwise this looks good. I will take care of the edits.
