### ISSUE TITLE
Create SQL Injection Challenge.

### ISSUE THREAD

**Issue by colbycocking** [acasi-ctf/ctf#37]
- [x] Write challenge description
- [x] Write challenge
- [x] Write documentation in .md file

**Comment by EllisHZH** [comment]
Summary of challenge 4. It is Morse Code challenge. The challenge will create 10 letter random string encode by Morse code table. User need to find out the original string.

**Comment by colbycocking** [comment]
This is supposed to be a SQL injection attack.

**Comment by colbycocking** [comment]
> 
> 
> Summary of challenge 4. It is Morse Code challenge. The challenge will create 10 letter random string encode by Morse code table. User need to find out the original string.

This is supposed to be the SQL injection issue. I have updated the title to better reflect this. All of your cipher challenges will go in the cipher challenge issue.

**Comment by EllisHZH** [comment]
Oh, i see, that is my fault

**Comment by colbycocking** [comment]
It's fine. I just want to make sure everyone is on the same track.

**Comment by EllisHZH** [comment]
SQL Injection  - Phrase 1 - 0.1 ver. The index page is set up. The injection page created. Database built which has "note" with "id", and "note", and "flog" with "flag-number". Need to do: Show up the "note" in the injection page. Write an basic SQL language doc. Modify the page, such as using .css.

**Comment by lgorence** [comment]
Pushing this to sprint 3.

**Comment by EllisHZH** [comment]
SQL Injection - Phrase 1 - 1.0 ver. The first challenge is done. Test step by step. It can reach to the flag. Need doc for the challenge. Thinking about make an other challenge which is more basic.

**Comment by EllisHZH** [comment]
SQL Injection - Phrase 1 - 2.0 ver. Add a very simple challenge to the index.php page. Challenge description is done.
