### ISSUE TITLE
Create Cumulative Challenge

### ISSUE THREAD

**Issue by colbycocking** [acasi-ctf/ctf#38]
- [x] Write challenge description
- [x] Write challenge
- [x] Write documentation in .md file. Most of this documentation should exist from the other challenges.

**Comment by EllisHZH** [comment]
Summary of Cumulative Challenge. It is Mix challenge base on the Classical cipher. The flag is "YOU GOT THE FlAG". The flag is encode by Caesar cipher, reverse cipher, and letter to number cipher. User need to decode step by step to get the flag.

**Comment by colbycocking** [comment]
Zhaohu wrote a small challenge set which includes a cumulative challenge. Closing as complete.
