### ISSUE TITLE
Figure out on how to resize the Terminal

### ISSUE THREAD

**Issue by DungLe2911** [acasi-ctf/ctf#39]
The terminal is not sizing properly, which it cause the content container to smush together. Also, make this to go all the  way down to the bottom. Currently it is 1/3 of the UI
- [ ] #40

**Comment by lgorence** [comment]
Probably (?) blocked by #40

**Comment by colbycocking** [comment]
Moving to sprint 3 because this is not important enough to focus on right now.

**Comment by lgorence** [comment]
Fixed by #61.
