### ISSUE TITLE
As a user, I want to be able to create an account so that I can track my progress. 

### ISSUE THREAD

**Issue by EthanIsakson** [acasi-ctf/ctf#4]
# Acceptance Criteria

- [x] User can create an account that they can log into. 
- [x] ~~Account keeps track of completed challenges.~~

**Comment by colbycocking** [comment]
- [ ] design UI components for creating account
- [ ] Come up with required elements for account creation.
- [ ] work with Logan to get UI to make correct system calls.

**Comment by lgorence** [comment]
We are splitting this issue into two, account creation and state tracking. New issue is #44. Closing this one, as it is now complete.
