### ISSUE TITLE
Figure out how to communicate UI with backend for data schema retrieval

### ISSUE THREAD

**Issue by DungLe2911** [acasi-ctf/ctf#41]
Currently, the component's detail such as paeg's path, label, title, icon is stored in JS data file. We need to figure it this out so in the future it can retrieve data from database instead from a javascript file

**Comment by colbycocking** [comment]
We don't have a back end for it to talk to yet. This is something I believe Logan and I are going to start on tomorrow.

**Comment by DungLe2911** [comment]
I just put this here as something that we might work on in the future so I dont forget about it. Thats why I label it is Sprint #3

**Comment by lgorence** [comment]
Pull request #33 should allow you to get started with this.

**Comment by colbycocking** [comment]
Can we close this ticket? I don't know if Richard is successfully making those API calls or not.

**Comment by DungLe2911** [comment]
if you are asking about implementation, then it is a no. Idea on how to successfully get to that point? - then yes

**Comment by colbycocking** [comment]
making successful api calls
