### ISSUE TITLE
Rework Docker Images 

### ISSUE THREAD

**Issue by EthanIsakson** [acasi-ctf/ctf#55]
Currently my docker images are pretty large for @lgorence to effectively store and spin up. Need to walk back through those images and scale down the contents that I do not need.

**Comment by lgorence** [comment]
You don’t have to build from scratch, you can use the existing DVWA image as a base image in your Dockerfile and just patch whatever you need to.

**Comment by EthanIsakson** [comment]
Understood, compiling a zip of only the files I need to be changed, will write mock up for Run Docker File

**Comment by colbycocking** [comment]
@EthanIsakson How is your progress on this issue going?

**Comment by EthanIsakson** [comment]
I went back through m y docker images and grabbed all the customized files so I can manually copy them in Docker File. I have mock ups of docker file configs. Just need a little more research to figure it out

**Comment by lgorence** [comment]
@EthanIsakson is this complete now? I'm not really sure what it's in reference to, and it looks like it was closed/reopened.

**Comment by colbycocking** [comment]
@EthanIsakson edit this issue to the correct user story format or issue format as necessary.
