### ISSUE TITLE
Erorr with auth0 on same network

### ISSUE THREAD

**Issue by DungLe2911** [acasi-ctf/ctf#73]
After we got auth0 implemented, it works fine on the machine that I use for dev. However, I was trying to see how the page looks like from a different PC on same network, I am not able to get the page load. Instead, I see this error: 
![2q58ef87z76dwrdt42cl](https://user-images.githubusercontent.com/59951881/115184730-4dc00a80-a093-11eb-8274-4179ec2ad4ef.png)

I am not sure this is something that we should worry about so I just leave it as a bug

**Comment by lgorence** [comment]
You can't use Auth0 over a non-secure connection __unless__ it's localhost. This is not something that we can really workaround.
