### ISSUE TITLE
Create Turn in Flag button

### ISSUE THREAD

**Issue by colbycocking** [acasi-ctf/ctf#93]
Create a button on the top bar that acts as the flag turn in. Players should be able to click the button which creates a dialogue box where they can enter the flag.

Player should then get feedback on whether the flag was correct or not.

If the flag is correct, mark challenge as complete for that player.

**Comment by DungLe2911** [comment]
Need Visuallize (mat in figma) on how/where the button should be in page.

**Comment by DungLe2911** [comment]
[ ]: able to display the flag
[ ]: display flag based on whether or not there is a property in API of the challenge
[ ]: ability to check if the flag input matched with the valye from API

**Comment by lgorence** [comment]
Not 100% complete yet, but button is present. Pushing rest of the tasks to next sprint.

**Comment by lgorence** [comment]
This should be complete as of tonight with the merging of #176.
